# Generated by Django 3.2.23 on 2023-11-13 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='humidityReading',
            new_name='humidityData',
        ),
    ]
